from os.path import expanduser
home = expanduser('~')
Program("EchoServer", ['EchoServer.cpp', home + "/opensource/cgicc-3.2.9/contrib/FCgiIO.cpp"], CPPPATH=[home +  "/opensource/cgicc-3.2.9/contrib"], CCFLAGS='-g', LIBS=['cgicc', 'fcgi', 'fcgi++', 'boost_thread', 'boost_system', 'boost_program_options'])
